<a href="https://colab.research.google.com/github/benjatussy/estadisticadescriptiva/blob/main/Laboratorio_0_Introducci%C3%B3n_a_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Pandas

## Objetivo:

Explorar las funciones básicas de la biblioteca Pandas en Python para cargar, visualizar y manipular estructuras de datos tipo DataFrame.

*Nota: Este laboratorio está diseñado para desarrollar razonamiento estadístico. Evita el uso de herramientas de IA para responder las preguntas a menos que esto sea explícitamente sugerido* 🤖. *En su lugar, enfócate en aplicar los conceptos revisados.*

## Actividad 1

Antes de comenzar a trabajar con bases de datos más complejas, aprenderás a crear tus propios datos dentro de Python usando Pandas. Esto te permitirá entender mejor cómo funciona un DataFrame y practicar operaciones básicas de conteo y selección.

1. Crea un DataFrame con los siguientes datos de estudiantes:

<center>

|Nombre| Edad (años)| Carrera|
|------|:-----------:|--------|
|Rodrigo | 21 | Informática|
|Pedro | 23 | Telecomunicaciones|
|Ignacia | 20 | Informática|
|Luis | 24 | Informática|
|Valentina | 22 | Analista|
|Carlos | 20 | Telecomunicaciones|
|Martina | 22 | Analista|
|Javiera | 21 | Telecomunicaciones|
|Camilo | 20 | Informática|
|Bastián | 20 | Informática|

</center>

Luego, muestra en la consola el contenido completo del DataFrame.

In [ ]:
import pandas as pd

In [ ]:
Nombre = pd.Series(['Rodrigo', 'Pedro', 'Ignacia', 'Luis', 'Valentina', 'Carlos', 'Martina', 'Javiera', 'Camilo', 'Bastián'])
Edad = pd.Series([21,23,20,24,22,20,22,21,20,20])
Carrera = pd.Series(['Informática', 'Telecomunicaciones', 'Informática', 'Informática', 'Analista', 'Telecomunicaciones', 'Analista', 'Telecomunicaciones', 'Informática', 'Informática'])

TABLA = pd.DataFrame({
    'Nombre': Nombre, #Primera columna
    'Edad(años)': Edad, #Segunda Columna
    'Carrera': Carrera #Tercera columna
})

print(TABLA)

      Nombre  Edad(años)             Carrera
0    Rodrigo          21         Informática
1      Pedro          23  Telecomunicaciones
2    Ignacia          20         Informática
3       Luis          24         Informática
4  Valentina          22            Analista
5     Carlos          20  Telecomunicaciones
6    Martina          22            Analista
7    Javiera          21  Telecomunicaciones
8     Camilo          20         Informática
9    Bastián          20         Informática

2. Muestra únicamente la columna "Carrera" del DataFrame creado en el inciso anterior.

In [ ]:
(TABLA['Carrera'])

0           Informática
1    Telecomunicaciones
2           Informática
3           Informática
4              Analista
5    Telecomunicaciones
6              Analista
7    Telecomunicaciones
8           Informática
9           Informática
Name: Carrera, dtype: object

3. ¿Cuántos estudiantes hay en cada carrera? Utiliza alguna función de Python para responder.

In [ ]:
estudiantes = (TABLA['Carrera'].value_counts())
estudiantes

Carrera
Informática           5
Telecomunicaciones    3
Analista              2
Name: count, dtype: int64

4. ¿Cuál es la edad más común entre los estudiantes?

In [ ]:
edades = (TABLA['Edad(años)'].value_counts().head(1))
edades

Edad(años)
20    4
Name: count, dtype: int64

5. Se espera que estos estudiantes egresen de su carrera en aproximadamente 3 años más. Agrega una nueva columna al DataFrame llamada "Edad al egresar" que contenga la edad que tendrá cada estudiante al finalizar sus estudios. Luego, muestra en la consola el DataFrame actualizado.

In [ ]:
TABLA['Edad al egresar'] = (TABLA['Edad(años)'] + 3)
print(TABLA)

      Nombre  Edad(años)             Carrera  Edad al egresar
0    Rodrigo          21         Informática               24
1      Pedro          23  Telecomunicaciones               26
2    Ignacia          20         Informática               23
3       Luis          24         Informática               27
4  Valentina          22            Analista               25
5     Carlos          20  Telecomunicaciones               23
6    Martina          22            Analista               25
7    Javiera          21  Telecomunicaciones               24
8     Camilo          20         Informática               23
9    Bastián          20         Informática               23

## Actividad 2

Eres parte del equipo de soporte de datos de una empresa de telecomunicaciones. Te han pedido cargar una base de datos de clientes y realizar una primera revisión para comprender su estructura y conocer su contenido.

Descarga la base de datos **<a href="https://docs.google.com/spreadsheets/d/1v6euDfqECe1HTJz0yFUrn7mmrt-rG9gG/export?format=xlsx
">aquí</a>** y sigue las instrucciones detalladas a continuación:

In [ ]:
from google.colab import files

files.upload()

Saving Base0.xlsx to Base0 (1).xlsx

{'Base0 (1).xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00b\xee\x9dh^\x01\x00\x00\x90\x04\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x94\xcbN\xc30\x10E\xf7H\xfcC\xe4-J\xdc\xb2@\x085\xed\x82\xc7\x12*Q>\xc0\xc4\x93\xc6\xaac[\x9eii\xff\x9e\x89\xfb\x10B\xa1\x15j7\xb1\x12\xcf\xdc{2\xf1\xcdh\xb2nm\xb6\x82\x88\xc6\xbbR\x0c\x8b\x81\xc8\xc0U^\x1b7/\xc5\xc7\xec%\xbf\x17\x19\x92rZY\xef\xa0\x14\x1b@1\x19__\x8df\x9b\x00\x98q\xb7\xc3R4D\xe1AJ\xac\x1ah\x15\x16>\x80\xe3\x9d\xda\xc7V\x11\xdf\xc6\xb9\x0c\xaaZ\xa89\xc8\xdb\xc1\xe0NV\xde\x118\xca\xa9\xd3\x10\xe3\xd1\x13\xd4ji){^\xf3\xe3-I\x04\x8b"{\xdc\x16v^\xa5P!XS)bR\xb9r\xfa\x97K\xbes(\xb83\xd5`c\x02\xde0\x86\x90\xbd\x0e\xdd\xce\xdf\x06\xbb\xbe7\x1eM4\x1a\xb2\xa9\x8a\xf4\xaaZ\xc6\x90k+\xbf|\\|z\xbf(\x8e\x8b\xf4P\xfa\xba6\x15h_-[\x9e@\x81!\x82\xd2\xd8\x00Pk\x8b\xb4\x16\xad2n\xcf}\xc4?\x15\xa3L\xcb\xf0\xc2 \xdd\xfb%\xe1\x13\x1c\xc4\xdf\x1bd\xba\x9e\x8f\x90dN\x18"m,\xe0\xa5\xc7\x9eDO97*\x82~\xa7\xc8\xc9\xb88\xc0O\xedc\x1c|n\xa6\xd1\x07\xe4\x04E\xf8\xff\x14\xf6\x11\xe9\xba\xf3\xc0B\x10\xc9\xc0!$}\x87\xed\xe0\xc8\xe9;{\xec\xd0\xe5[\x83\xee\xf1\x96\xe9\x7f2\xfe\x06\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xb5U0#\xf4\x00\x00\x00L\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92MO\xc30\x0c\x86\xefH\xfc\x87\xc8\xf7\xd5\xdd\x90\x10BKwAH\xbb!T~\x80I\xdc\x0f\xb5\x8d\xa3$\x1b\xdd\xbf\'\x1c\x10T\x1a\x83\x03G\x7f\xbd~\xfc\xca\xdb\xdd<\x8d\xea\xc8!\xf6\xe24\xac\x8b\x12\x14;#\xb6w\xad\x86\x97\xfaqu\x07*&r\x96Fq\xac\xe1\xc4\x11v\xd5\xf5\xd5\xf6\x99GJy(v\xbd\x8f*\xab\xb8\xa8\xa1K\xc9\xdf#F\xd3\xf1D\xb1\x10\xcf.W\x1a\t\x13\xa5\x1c\x86\x16=\x99\x81Z\xc6MY\xdeb\xf8\xae\x01\xd5BS\xed\xad\x86\xb0\xb77\xa0\xea\x93\xcf\x9b\x7f\xd7\x96\xa6\xe9\r?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xea2[\'\xc2\x03\x00\x00\x1e\t\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xacU\xedn\xa38\x14\xfd\xbf\xd2\xbe\x03\xe2?\xc5&@\x005\x1dA \x9aJ\xcd\xa8\xcad\xda\x1d)\xd2\xc8\x01\'x\x0b\x985&\x1f\xaa\xe6\x91\xf6)\xf6\xc5\xf6\x9a\x84\xb4\x9d\xacV\xd9\xceV\xa9\x8d\xed\xeb\xe3s\xef=\xd7\xbe\xfe\xb0+\x0bmCE\xc3x5\xd2\xf1\x15\xd25Z\xa5<c\xd5z\xa4\x7f\x99O\x0cO\xd7\x1aI\xaa\x8c\x14\xbc\xa2#}O\x1b\xfd\xc3\xcd\xaf\xbf\\o\xb9xZr\xfe\xa4\x01@\xd5\x8c\xf4\\\xca:0\xcd&\xcdiI\x9a+^\xd3\nVV\\\x94D\xc2P\xac\xcd\xa6\x16\x94dMN\xa9,\x0b\xd3B\xc85K\xc2*\xfd\x80\x10\x88K0\xf8j\xc5R\x1a\xf3\xb4-i%\x0f \x82\x16D\x02\xfd&gu\xd3\xa3\x95\xe9%p%\x11Omm\xa4\xbc\xac\x01b\xc9\n&\xf7\x1d\xa8\xae\x95ip\xbb\xae\xb8 \xcb\x02\xdc\xdeaG\xdb\t\xf8\xb9\xf0\x8f\x114V\x7f\x12,\x9d\x1dU\xb2T\xf0\x86\xaf\xe4\x15@\x9b\x07\xd2g\xfecdb\xfc&\x04\xbb\xf3\x18\\\x86d\x9b\x82n\x98\xca\xe1\x89\x95p\xdf\xc9\xca=a\xb9/`\x18\xfd4\x1a\x06iuZ\t x\xefDsN\xdc,\xfd\xe6z\xc5\n\xfap\x90\xaeF\xea\xfa\x13)U\xa6\n]+H#\x93\x8cI\x9a\x8d\xf4!\x0c\xf9\x96\xbe\x99\x10m\x1d\xb5\xac\x80U\xcb\xf3\xac\xa1n\xde\x9c\xe4|/\xb4\x8c\xaeH[\xc89\x08\xb9\x87\x07Cd\r\x10R\x96 \x8c\xb0\x90TTD\xd21\xaf$\xe8\xf0\xe8\xd7\xcfj\xae\xc3\x1e\xe7\x1c\x14\xae\xcd\xe8\x1f-\x13\x14\n\x0b\xf4\x05\xbeBK\xd2\x80,\x9b{"s\xad\x15\xc5H\x1f\x07\x8b/\r\xb8\xbf\xd8o\xe8\x9a,b\xda<I^/\xbe\xd2\xa2b2_\xc4-O\x17\t\xd4n\xf6\xd7\x9f\x8dd)\xd1\xc0"\x15\xac\x96lC\xb4\x94W\xda\xfd^\xe6\xbcR\x1b\x89\x10\xbc(8\xb8\x0e\xb1\xd3H\xc3\xd6\xe0]+\x886\r\xe76\xb6\xf1\xe2\x8e,\xa1\x14$\x17\x8ckh\xf1J\xfa\xe4\xbc\xce\xfe\x83\xf8I\xaa"jBH\x0fn\x1f\xbe\x7f\x0c/x/\x82^\xe0\xf7Rh\xf0}\x1b\xdfA\x92?\x93\r\xa4\x1c\x84\x95\x1do\x84[\xc8\xa9\xf7\xed\xd9w\x87\xbe3\xf4=\x03\r\x07\xaea;Vdx\xee``$~hEQ\xe2&a\x18}\x07/\x84\x1b\xa4\x9c\xb42?\xcaHa\x8et\x1b4s\xb64%\xbb~\x05\xa3\xa0e\xd9\xcb\xf9\xcf\xe8\xf8g\xa8\xfe\x87\xa6_\xfb\xae<U\x17\xe6\x03\xa3\xdb\xe6Epj\xa8\xed\x1eY\x95\xf1\xad\xd2\xa3\xeb\x81;\xfb~l`\x0b\x86\xdbn\xf5\x91e2\x87;\xda\xb7\xed\xd3\xdcG\xca\xd69P\xc6\xb6\xa7\xf6Ae)j#\xfd\xd9s\xc7Q\xe8\xa2\xd8\xc0IlC\x04pbx\x96;4\x9ch\xe2 la4\xb1\xac\x8e\x92\xf9\x8aSw7\x03\xb7\xae\xd7\xaa\xae\x9e>\xf2\xdf\t\x867@]\xdb*\xba\xf0-\x02u\x84\xb8\xcdp\x97\xbd~WJ\x8a\x14\xcaGu\x9d\xa1\x8f\x91\xe5+\x0b\xba\x93w\x8d\xeczP.\x03v\xd8F\xe1\x10\xf9\xb6\x81\x92\x81c\xd8\x9eo\x19\x9e=\xb0\x8c\xb1\x1d[\x893L\xe2$rT~\xd4\xd3\x12\xfc\x1f\x17lW@A\xfff)\x969\x11r.H\xfa\x04/\xdd\x8c\xae"\xd2\x80\x92\x0e\x0e\x01\xdf\xd7d#\xc7\x8b\xd0\x00(\xda\x13<1l\xec##\x8a\\\xdbp\xe2\xc9\xc0\x19\xe2x\x9c8\x93\x17\xb2\xca\xfd\xd5;\xaf7\xcf\xecvSU{\xf0\xce\x02\xe9n\x1c\xa8vr\x9c=M\xae\x0e\x13\xc74\xbd)\xba`\x16\xab\xb8\x1fw\xff\x9b\xe1g\xf0\xbe\xa0\x17\x1aO\x1e.4\x1c\x7f\x9a\xce\xa7\x17\xda\xde%\xf3o\x8f\x93K\x8d\xc3i\x14\x87\x97\xdb\x87\xb3Y\xf8u\x9e\xfc\xd6\x1fa\xfec@\xcd.\xe1\xaa\xeddj\xf62\xb9\xf9\x1b\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x81>\x94\x97\xf3\x00\x00\x00\xba\x02\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xacRMK\xc40\x10\xbd\x0b\xfe\x870w\x9bv\x15\x11\xd9t/"\xecU\xeb\x0f\x08\xc9\xb4)\xdb&!3~\xf4\xdf\x1b*\xba]X\xd6K/\x03o\x86y\xef\xcd\xc7v\xf75\x0e\xe2\x03\x13\xf5\xc1+\xa8\x8a\x12\x04z\x13l\xef;\x05o\xcd\xf3\xcd\x03\x08b\xed\xad\x1e\x82G\x05\x13\x12\xec\xea\xeb\xab\xed\x0b\x0e\x9as\x13\xb9>\x92\xc8,\x9e\x148\xe6\xf8(%\x19\x87\xa3\xa6"D\xf4\xb9\xd2\x864j\xce0u2js\xd0\x1d\xcaMY\xde\xcb\xb4\xe4\x80\xfa\x84S\xec\xad\x82\xb4\xb7\xb7 \x9a)f\xe5\xff\xb9C\xdb\xf6\x06\x9f\x82y\x1f\xd1\xf3\x19\tI<\ry\x00\xd1\xe8\xd4!+\xf8\xc1E\xf6\x08\xf2\xbc\xfcfMy\xcek\xc1\xa3\xfa\x0c\xe5\x1c\xabK\x1e\xaa5=|\x86t \x87\xc8G\x1f\x7f)\x92s\xe5\xa2\x99\xbbU\xef\xe1tB\xfb\xca)\xbf\xdb\xf2,\xcb\xf4\xeff\xe4\xc9\xc7\xd5\xdf\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00U\xd4g\xad+\xec\x05\x00\xde\xe01\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\x9c\x93A\x8f\x9b0\x10\x85\xef\x95\xfa\x1f,\xdf\x891!4\x8b +6\xd9\xa8{\xab\xdam{6f\x08V0\xa6\xb6\xb3IT\xf5\xbf\xef@\x94\xa4R.\xd1J \x99\xb1\xfd\xbdy\xf6#{<\xe8\x96\xbc\x81u\xcat9\xe5\x93\x90\x12\xe8\xa4\xa9T\xb7\xc9\xe9\xcf\xd7u0\xa7\xc4y\xd1U\xa25\x1d\xe4\xf4\x08\x8e>.>\x7f\xca\xf6\xc6n]\x03\xe0\t\x12:\x97\xd3\xc6\xfb>e\xcc\xc9\x06\xb4p\x13\xd3C\x873\xb5\xb1Zx\xfc\xb4\x1b\xe6z\x0b\xa2\x1a7\xe9\x96Ea\x980-TGO\x84\xd4\xde\xc30u\xad$\xac\x8c\xdci\xe8\xfc\tb\xa1\x15\x1e\xfbw\x8d\xea\xdd\x99\xa6\xe5=8-\xecv\xd7\x07\xd2\xe8\x1e\x11\xa5j\x95?\x8ePJ\xb4L_6\x9d\xb1\xa2l\xd1\xf7\x81\xc7B\x92\x83\xc5\'\xc2wz\x96\x19\xeb7JZIk\x9c\xa9\xfd\x04\xc9\xec\xd4\xf3\xad\xfd\x07\xf6\xc0\x84\xbc\x90n\xfd\xdf\x85\xe11\xb3\xf0\xa6\x86\x0b\xbc\xa2\xa2\x8f\xb5\xc4g\x17Vt\x85M?\x08K.\xb0\xe1\xb8l\xbaSUN\xff\xae\x9e\x93\xd5S<O\x82Y\xc2\xa3 \x8e\x0b\x1e\x14\xcfK\x1e\xac\x8b/\xd3yT,\xe3\xf5\xfc\xe9\x1f]d\x95\xc2\x1b\x1e\\\x11\x0buN\x0b\x9e\xbe\xc6<\x0c)[dc\x84~)\xd8\xbb\xff\xc6\xc4\x8b\xf2\x07\xb4 =\xa0\x0c\xa7dHhi\xccvX\xf8\x82\xa5\x10\xa1n\\0@\xdd\x9f\x1b,\xbbp\x17\xd9u|\xd6X\x8fI\xfefI)\x1c,M\xfb[U\xbeA!\xfcc*\xa8\xc5\xae\xf5\xdf\xcd\xfe+\xa8M\xe3\xb1\x1aOf\xe8y\x08MZ\x1dW\xe0$\xa6\x15[\x98Lgh\xe0\x1d\x00\x00\xff\xff\x00\x00\x00\xff\xff\x94}\xeb\x92+\xb7\x91\xf4\xab(\xf4\x00\xc7l\x92\xcd\x8bCV\xc4\x8e\xcf\xf02\xec\x8b\xa9\xe1\x0b(\xb4\x8a\xf8~\xf9\xdb\xb0\x1c\xde\xdd\xb7\xdfbOO\x0fP\x99F%\xce/\xd9\xcc\xc9\x02\x1a\x95\xb8%\xd0\xfd\xd3\x1f\xff\xef\xf7\xdf\xff\xf9\xfd\xd7\x7f\xfe\xfa\xf3O\xff\xf8\xff\xff\xfd\xc3?\xfe\xf2c\xf3\xe3\x0f\x7f\xfc\xd7\xaf\x7f\xff\xc3\xfe\xeb\xcf\xeb\xd5\x8f?\xfcO\xb3\xfd\xf5\xb7?\xff\xe7\xff~\xff\xfd\x8f\xdf~\xff\xfb?\xff\xf2\xe3\xea\xdb\xa6\xfd\xf1\xe7\x9f~{\x82\xff\xe3\x89\x9e\xfe\xc6~\xf8\xc3\xfe\xdf\x7f\xfd\xbc\xfa\xe9O\xff\xfa\xf9\xa7?\xfd6#^\x10\xd1\xe4\x88\xbf"b\x9d#\xbe#b\x93#^\x11\xb1\xcd\x11\'D\xb49\xe2\x8c\x88]\x8e\xb8 b\x9f#\xae\x888\xe4\x887D\x1cs\xc4\x8d<1\xf7P;\x02qO\xb5\'\x10\xf7X\x07\x02q\xcfu$\x10\xf7`\xffF \xee\xc9\xde\t\xc4=\xda_\x08\xc4=\xdbw\x02q\x0f\xf7A _O\xf7O\x96\xe1K\x9a\xaf\xab\xd2\xfc\x89\xce\xd3|\xed\xf3\x9c@|\xa2\x7fB\x88L\xbe\x93?w\xcd\xf5J \xae\xb9Ni\x04\x17\xfd\x1c\xff\xf9\x85@\\k_\t\xc4\xb5\xf6[\x1c\xe8\x16C\xba\x18\xd2\xc7\x90!\x86\x8c\x04\xe2\x92\xf3oq\xe3\xdc\t\xc4\xe5\xef/i\xe3\xac\x8f\xdf\x0e\xee\xb9\xbd\x07\xbf?\x8au\xc9\x92{S\x95\xdcO\xb4Kn\xa7\xab\x17\x02q\xbd\xd6_?!,\xb9\xc9\x9f\xfb\x0e<\x86\x9c\xd2\x08\x1b\x97\x97g\xf2\xf7N?\x978\xc4\x95@|v\xc7\x81n1\xa4\x8b\xcb\xd2\xc7\x90!\x86\x8c\x08\xd9\xb8\x9e\xebo1\xcb\x9d\xb0\xb8\xee\xe5\x97\xb4u\xda\xdd\xb7\xa3\xcf\xee\xf4\xf7\xe6p8~s\x80G\xb1\x18Yzo\xab\xd2\xfb\x89\xce\xd3{\xe32\xe3\x05!k\x9f\xde\x9f\x10\x96\xde\xe4\xcf}z\xc7\x90S\x1a\xc1\x15\xf0L\xfe\xdcgw\x1c\xe1J >\xbb\xe3@\xb78P\x17C\xfa\x182\xc4\x90\x91@|\xdf\x1d\xd7\xe8N2\xc4gw\xda8\xed\x06\xfb\xee\xf4\xf7fu\xf8\xd6\xf8\xec.\x16#\xcb\xee\xb6*\xbb\x9fh\x97\xdd.\xf7^\x10\x02\xd9\xfd\ta\xd9M\xfe\xdcgw\x0c9\xa5\x11\xb6~\xe6\x1d\xff\xfd\x85@\xfc\xd4\x84@|z\x13\x88\xd3\xd1-\x86t1\xa4\x8fk4\xc4\x90\x914\xae\xef\xbcc\x96;aq\x8f\xee\x97\xacu\xd6\xdf\\\xfb\xbe\xa7?7\x87\xed\xea\xdb\xde\xa7w\xb1\x18Yz\xef\xaa\xd2\xfb\x89v\xe9\xedB\xbf d\xed\'\xde\x9f\x10\x96\xde\xe4\xcf}z\xc7\x90S\x1a\xc1w\xde\xe4\xcf}\xe7\x1dG\xb8\x92\'\xe1\xba\xba\xb7\x98\xe5\x16C\xba\x18\xd2\xc7\x90!\x86\x8c\x04\xe2;\xef\xf8\xd1\xdd\t\xc4O\xbc\xd3\xc6\xd9[\xf2\xe6\xeb\xed\xf7\xf4\xe7\xa6m\xbe\xed|r\x17K\x91%\xf7\xbe*\xb9\x9fh\x97\xdc\xael/\x08\x81\xe4\xfe\x84\xb0\xe4&\x7f\xee\x93;\x86\x9c\xd2\x08nep&\x7f\xee\x93;\x86\\\xc9\x93\xf0\xc9\x1d\x97\xf3\x16\x07\xeab\x96>f\x19b\xc8H >\xb9c\x96;\x81\xf8\xe4N\x1b\xe7x\x84\xe4}\xcf\x1ao\xbd\x82iw\xb1\x14Yr\x1f\xaa\x92\xfb\x89v\xc9\xedW\x95\x08\x81\x89\xc9\'\x84%7\xf9s\x9f\xdc\x04\xe2\xb2\xf3\x94FX\xfb\xae;\xfe\xfbK\x0c\xb9\x92G\xe1\xb3;\xae\xcb-\x86t1\xa4\x8f\x8b;\xc4,#\x81\xf8\xec\x8e\x03\xdd\xc9sq\xcb\xae_\xd2\xd6\xb15\xa3\x1b\xd8\xdf\xd3\x9f\x9b\xe3\xf6\xf8\xcdMl\x1e\xc5\xbad\xd9}\xac\xca\xee\':\xcf\xee\xad\xdf\x10D\x08t\xdd\x9f\x10\x96\xdd\xe4\xcf}v\xc7\x90S\x1a\xa1q%<\xc7\x7f\x7f!\x10?\xed&\x10?\xed&\x10?\xed\x8e\xcb\xd2\xc5\x90>\x86\x0c1d$\x10\x9f\xdd1\xcb\x1d!\x1b\xbf\xaaL[\xc7v\x04\xfd\xac\xfa=\xfd}\xb3j\xbe\x1d\x8e\xc9?\xbf\xf7],R\x96\xea\x8d\xd9:5\x1e\xcf\x13\xee\x92\xdd\xd5\xe4e\xa2t\x9b\x88\xe0\xf3|\xf2\xb0tg\x04~\x03\x9ca\xfc\x0e\xf8\x82y\x06Y\xfb\xd9\x8a\x10\xe5"`\xae\x04\xb3\xf1]\xbaP\xda\x9b\x10\xab\x130\xbd\x80\x19\x04\xcc\xc80>\xf5\x05\x9e;\xc3\xf8\x89K\xd6R\xcdj\xfb\xcd5\xd6{\x06\xd8\xac\xb6\xbbo+?3/\x97%O\xfa\xa77Tal\xa2\x95\xb4\xf5\xdb\x86\rb`\x02\xb3`h\xd2\x13\x02p6\t\xc6\xcfa\xb2 ;?\x89a\xc5\xf4st\x86q%\xb92\x8c\xef\xe9\x85X7!V\'`z\x013\x08\x98\x91``\x8f\\\xe0\xb93\x1e\xbf\xd1\x92\xb5\x94m\x93\xfb}\xc2\xf7\x0c\xb0\xd9\x1e\xf6\xb0\x93\xfe(\x97%O\xfa\xa7gT\x91\xf4h1m\xfdnbCl(\xbfY\xbe`h\xd2\xc7n\xda+\x0b\x02I\x9f\xfae\x8d+\xe6Y`\xb80\x0c$=)-$}\\\xa3\x9b\x10\xab\x130\xbd\x80\x19\x04\xcc\xc80\xd0\xd3\x0b\xbe\'\xe1\x81iN\x96\x0e6I\x07o(\x03\xb4\x96\xf3\xdbv\xf5\xf5\x0f:}\xdd\x08m\x9e\xa6RE\xfe\xa3\x07\xb5u\n~\x99(\xddL\x07\xf2?5\xbb\xdc\xac\xfb;#\x80N?\xf6\xe4N\x0b\xcfSd\x8dk\xbb3\x8b\x02\x9d~\x1c\xe5*\x94\xf6\x8d`\xfc\x16\xffM\xc0t\x02\xa6\x170\x83\x80\x19\x19\x06\xf2_pF\t\xcf\xc6/b\xf3\x96:\x90\xfcO\xf3e\xb3\xde\xf9\xa9\xd0\xa3\xdc\ny\x97\xfft\x9a*R\x1e\x8d\xa9\xad\xdf\x84l\x88y\x05)\x9f:`\x90\xf2\xb1\t\xf7\xca\x82\xc0\xe4>\xb3\xe1`r\x1fG\xb9\xb0(N\x16W\x82\xc1\xc9}lN\xde\x84X\x9dP\xeb^\xe0\x19\x04\xcc\xc8\xea\xe5\xed$\xa1<w\xc6\x03)\x9f\x1b\xa2\xcf3\x83n\xd7}ayv_\xed\xee\xd0\xf8\xcd\x9dG\xb9,y\xd2?\xfd\xa7\x8a\xa4G\xbbj\xeb7\'\x1bbiA\xd2\xa7\xc6\x18$}l\xcd\xbd\xb2 \x90\xf4\x999\xe7\x8apf\x0c\xd0\xcf\xc7\x86\xe5\x95\xf0`\xd2\xc75\xba\t\xe5\xe9\x84Z\xf7\x02\xcf `F\x86\x81~>~>w\xf6|`r\x9f\xf9\xa4\xab\r8M\x0b\xc9\x94\xf3\xab\xcd\xce;\xad\x8fr\x95\xf2\x9c\x7f\xdaR\x159\x8f.\xd6\xd6%\xd3KC\x9c.\xc8\xf9\xd4.\x83\x9c\x8fm\xbfW\x16\x04r>\r\xb2\xf6\xc7\x05\x18\x03\xe4|\\\x92+\xe1\xc1\x9c\x8f-\xc8\x9bP\x9eN\xc0\xf4\x02f\x100#\xc3@\xce\x0b\xd6*\xe3\x81]\x9c\xcc=]\xb5\xde_z_H\xa6\r\xb9\xdd\x81\xed\xe2\x14\xdb*O\xfa\xa7]U\x91\xf4\xe8n\xb5p@\x9d8`\xb0u\x99\xbah\x90\xf4\xb1\x91\xf7\xda\xc4\x98\xd3\x82y>\xa9\x1dt\xf41\xc3E\x88r%\x18L\xfa8\xd6M\x88\xd5\t\x98^\xc0\x0c\x02f$\x98-$=\xa9\x97\xebz\xee\xec\xf9\xc0\xec&M\x87\xa6\xd9|\xf3]\xd4{\xd6\x96\xfb\xc3\xb1\xc5\x13a\xacR_\x85\xc9\xb3\xfeicUd=\xba^-l\xd8\x13g\x0c\xb2>\xb5\xd7 \xebc\x9b\xf0\xb5\x891\xa7\x053\x8d\x89\xb0w\x19\xdb\x88\x17!\xcaU\xc0\xbc\x11\x0c.c\xb1<\x1e\xd3\t<\xbd\x80\x19\x04\xccH0\xb8w\x19\xb7\xc2\x9d\xf1x\xb7*k);I\xe0\xcf\xc9\xbcg\x80f\xb5^\x93\xbdK\xdd\x90m\x9e\x86VE\xd2\xa3\xff\xd5\xc2\x86=\xf1\xc8`~\x93\x9an\x90\xf4\xb1\xef\xf7:\x95\xdbm\x10\xc1\xdee\x1ad\xefoj\x08\x0c\x17\x01s%\x18\xec\xeaI\x8d\xbc7+\xc4\xea\x18\xc6u\xad\xbd\xc03\x08\x98\x91`\xb0\xab\x17\x1cZ\xf6|`N\x9f\xb6T\xb3\xda\xe1\x9c>k\xca\xcda\r\x83\xc1\xa3\xfcl\xf2kIu\xd6\xec\xf3\x82\x9e\xb3f[\xbfaO0p\x10a\xc1\xb0\r{F\xe0\xadY\x01s\xca\x82\xc0a\x04\x81\xe1\xc20~\xc3\x9ea\xfc\x86\xbd\xc0s\x13\xca\xd3\t\x98^\x885\x08\x98\x91a\xfc\xfcF\xe0\xb9\x13\x0clXf-\xd5\xb6\xdf\\k\xbf\xe7\xbf\xaf\x0f\xb0\xbb\xf3(?\x99<\xe5\xeb\x8c\xd95\xfa\xa1\xad\xdf\xa3\'\x18L\xf9O\x1e\x9a\xf2\x821\xcb\x82\xf8u\xec\x82\x99\x16?p#/\xb6v/B\x94+\xc1@?/\xf0\xdc\x18\xc65}\'\xf0\xf4\x02f\x10b\x8d\x0c\x03)\x1f?\xc3;\xe3\x81\xcbyi:\x1cWp\xd4\xe0=k\xca\xe6\xb0\xb3\xc9M\xbe\xa3\xf9(W;\xcf\xf9:_v\x8d\x8eW\xeb\x8f\xc1\x13\x0c\x1cFX0\x93e\xe4.Y3\x02\xefK\t\x98S)\xc8Y \xb80\x0c\\C\x15lY!\xd6\x8da \xe5\x8b~\xe3t\x0f\xbe\x17b\rB\xac\x91a \xe5\x05[\x96\xf1@\xca\xa7\x06\xfa\x86\x1c\x1d\xceZ\x92\x00\x1e\xe5\x1a\xe5\x19_\xe7\xc4\xae\xd1zk\xddsx!\x18\xcc\xf8\x92\x13\xcb\x08`b#8\xb1\x0b\xcf$+\xbf\x84\x15\xa2\\\x18\x06&6qI\xde\x08\x0f,a\x05L\'`z\x013\x08\x98\x91``\t+<\x9f;\xe3\xf1\xb3\xf9\xbc\xa5\xec\x0e\xb63\xa5\xb2\xdf\xd7+2\x97/\x97$O\xf9:\'v\x8d\x96b\xeb\x9dX\x82\xc1\x94/9\xb1\x8c\x00:\xf9\xd8\xdb<-<d$9\xb3 ~\x7f^(\xc8U\xc0\xbc\x11\x0cf<\xf1\xb8\xdd\xf0\xd9\t<\xbd\x80\x19\x04\xcc\xc8\xea\x05\x9d|\xdc\x08w\xc2\x03go\xb2\x86\xb2M\x9bf\x9b\x9e!vS\x98\xf7*\xf4\xa3\xdc\xce\xb9\x16\xea\x0c\xda5:r\xad7h\t\x06\'\xf9%\x83\x96\x11@\xf7\x1f[\x9e\xa7\x85g\xda\xc1\xf4\xa7\x12\x84(\x17\x01se\x18X\xd7\n\x06-\xe3q=@\'\x94\xa7\x17x\x06\x013\x12\x0cl\xe6\x08\xe5\xb9\x13\x0c\xaek\xd3th\xed \x9a\xef\xfe\xd3\xdf7\xad\xb9Yn\xc9\xf6(\xd7(O\xf9:\x7fv\x8d&X\xeb\xfdY\x82\xc1\xee\xbf\xe4\xcf2\x02H\xf9\xd8\x19<-<\xcf\x94\xf76\xf2Y\x88ra\x18\x98\xf1\x90\x92@\xca\x0b\xfe\xac\x10\xab\x13\xca\xdc\x0b<\x83\x80\x19\x19\x06\xfa\xff\xd8\xbf\xbe\x13\x1eL\xf94\x1d,\xe5]\x9c\xf7\x99c=\xbd\xbbk}\xb4\xeb\xb1\xae\x15\x1e\xe5\x1a\xe5)_\xe7\xce\xae\xd1\x8e\xdb\xc1k\x95\x04wv\xe1\xa1[9\xb1\xe7\xf7J\n\xb2\x86\xad\x9c\xd4\xf3\xf3\x13\xd43c\x80)O\\\x92+\xe3\x81\x94\x17\xdcY\xa1F\x9d\x80\xe9\x05\xcc `F\x86\x81\x94\x8f\xebu\'<\xfeU@\xbfd\xe9`\xbb\x97\xae%\xdf\xe7\xdf?R\xbei7\xe6d\xf9\x9d\x9cbK\xe5)_g\xcd\xae\xd1\xff\xdayk\x96`\xb0\x97/Y\xb3\x8c\x00z\xf9\xd8X=-<S/\xef\xd6"g!\xcaE\xc0\\\t\x06w/c\x0b\xf3\xc6b\xc1\xc4&\xe6\xe9\x852\x0f\x02fd\x18H\xf9\xb8\x15\xee\x8c\x07\xb6r\xd2t\xb0[\xe0p\xdar&\xf9\xc8\xf9\xed\xde\x0e\xe1\xa7\x0b\x01\xc8\xffb\xb1\xf2\xfc\xafsi\xd7h

1. Sube la base de datos al entorno "Archivos" de Google Colab (ícono de carpeta en la barra lateral izquierda). Luego, cárgala en un DataFrame llamado `df_1`.

$\hspace{1 cm}$ *Nota: Recuerda que para cargar la base de datos a un DF debes utilizar la biblioteca Pandas de Python*.

In [ ]:
df_1 = pd.read_excel('Base0.xlsx')
print(df_1)

              ID     Género  Ciudadano mayor Pareja Dependientes  Antigüedad  \
0     7590-VHVEG   Femenino                0     Sí           No           1
1     5575-GNVDE  Masculino                0     No           No          34
2     3668-QPYBK  Masculino                0     No           No           2
3     7795-CFOCW  Masculino                0     No           No          45
4     9237-HQITU   Femenino                0     No           No           2
...          ...        ...              ...    ...          ...         ...
4094  9780-FKVVF  Masculino                0     No           No           6
4095  1919-RTPQD  Masculino                0     Sí           Sí           7
4096  5214-NLTIT  Masculino                0     Sí           Sí          72
4097  3345-PBBFH  Masculino                0     Sí           No           8
4098  5055-BRMNE   Femenino                0     Sí           Sí          67

     Servicio telefónico            Líneas múltiples Servicio de Internet  \
0                     No  No hay servicio telefónico                  DSL
1                     Sí                          No                  DSL
2                     Sí                          No                  DSL
3                     No  No hay servicio telefónico                  DSL
4                     Sí                          No         Fibra óptica
...                  ...                         ...                  ...
4094                  Sí                          No                  DSL
4095                  Sí                          No                  DSL
4096                  Sí                          Sí         Fibra óptica
4097                  Sí                          No                  DSL
4098                  Sí                          Sí         Fibra óptica

     Protección contra Malware Protección del dispositivo Soporte técnico  \
0                           No                         No              No
1                           Sí                         Sí              No
2                           Sí                         No              No
3                           Sí                         Sí              Sí
4                           No                         No              No
...                        ...                        ...             ...
4094                        Sí                         No              No
4095                        No                         No              No
4096                        No                         Sí              No
4097                        No                         No              No
4098                        Sí                         No              Sí

     Televisión en streaming Películas en streaming   Contrato  \
0                         No                     No  Mes a mes
1                         No                     No     Un año
2                         No                     No  Mes a mes
3                         No                     No     Un año
4                         No                     No  Mes a mes
...                      ...                    ...        ...
4094                      No                     Sí  Mes a mes
4095                      No                     No  Mes a mes
4096                      No                     Sí   Dos años
4097                      No                     No  Mes a mes
4098                      Sí                     Sí   Dos años

     Facturación sin papel                       Método de pago  \
0                       Sí                   Cheque electrónico
1                       No            Cheque enviado por correo
2                       Sí            Cheque enviado por correo
3                       No  Transferencia bancaria (automática)
4                       Sí                   Cheque electrónico
...                    ...                                  ...
4094                    Sí  Transferencia bancaria (automática)
4095                    No                   Cheque electrónico
4096                    Sí      Tarjeta de crédito (automática)
4097                    Sí  Transferencia bancaria (automática)
4098                    No      Tarjeta de crédito (automática)

      Cargos mensuales (dólares)  Cargos totales  (dólares) Deserción Cliente
0                          29.85                      29.85                No
1                          56.95                    1889.50                No
2                          53.85                     108.15                Sí
3                          42.30                    1840.75                No
4                          70.70                     151.65                Sí
...                          ...                        ...               ...
4094                       59.15                     336.70                No
4095                       44.75                     333.65                No
4096                       90.80                    6511.80                No
4097                       49.55                     393.45                No
4098                      106.70                    7009.50                No

[4099 rows x 20 columns]

2. Explora el contenido del DataFrame mostrando las primeras y últimas 10 filas.

In [ ]:
df_1.tail(10)
df_1.head(10)

,ID,Género,Ciudadano mayor,Pareja,Dependientes,Antigüedad,Servicio telefónico,Líneas múltiples,Servicio de Internet,Protección contra Malware,Protección del dispositivo,Soporte técnico,Televisión en streaming,Películas en streaming,Contrato,Facturación sin papel,Método de pago,Cargos mensuales (dólares),Cargos totales (dólares),Deserción Cliente
0,7590-VHVEG,Femenino,0,Sí,No,1,No,No hay servicio telefónico,DSL,No,No,No,No,No,Mes a mes,Sí,Cheque electrónico,29.85,29.85,No
1,5575-GNVDE,Masculino,0,No,No,34,Sí,No,DSL,Sí,Sí,No,No,No,Un año,No,Cheque enviado por correo,56.95,1889.50,No
2,3668-QPYBK,Masculino,0,No,No,2,Sí,No,DSL,Sí,No,No,No,No,Mes a mes,Sí,Cheque enviado por correo,53.85,108.15,Sí
3,7795-CFOCW,Masculino,0,No,No,45,No,No hay servicio telefónico,DSL,Sí,Sí,Sí,No,No,Un año,No,Transferencia bancaria (automática),42.30,1840.75,No
4,9237-HQITU,Femenino,0,No,No,2,Sí,No,Fibra óptica,No,No,No,No,No,Mes a mes,Sí,Cheque electrónico,70.70,151.65,Sí
5,9305-CDSKC,Femenino,0,No,No,8,Sí,Sí,Fibra óptica,No,Sí,No,Sí,Sí,Mes a mes,Sí,Cheque electrónico,99.65,820.50,Sí
6,1452-KIOVK,Masculino,0,No,Sí,22,Sí,Sí,Fibra óptica,No,No,No,Sí,No,Mes a mes,Sí,Tarjeta de crédito (automática),89.10,1949.40,No
7,6713-OKOMC,Femenino,0,No,No,10,No,No hay servicio telefónico,DSL,Sí,No,No,No,No,Mes a mes,No,Cheque enviado por correo,29.75,301.90,No
8,7892-POOKP,Femenino,0,Sí,No,28,Sí,Sí,Fibra óptica,No,Sí,Sí,Sí,Sí,Mes a mes,Sí,Cheque electrónico,104.80,3046.05,Sí
9,6388-TABGU,Masculino,0,No,Sí,62,Sí,No,DSL,Sí,No,No,No,No,Un año,No,Transferencia bancaria (automática),56.15,3487.95,No

3. ¿Cuántas filas y columnas tiene la base de datos? Responde utilizando solo una línea de código.

In [ ]:
filas = df_1.shape[0]
columnas = df_1.shape[1]

print("Filas: ", filas)
print("Columnas: ", columnas)

Filas:  4099
Columnas:  20

4. ¿Qué tipo de objeto es `df_1`? Justifica utilizando una función de Python.

In [ ]:
type(df_1)

pandas.core.frame.DataFrame

5. Usa la función `info()` para examinar el contenido  del DataFrame. ¿Qué tipo de datos contiene cada columna?

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4099 entries, 0 to 4098
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          4099 non-null   object
 1   Género                      4099 non-null   object
 2   Ciudadano mayor             4099 non-null   int64
 3   Pareja                      4099 non-null   object
 4   Dependientes                4099 non-null   object
 5   Antigüedad                  4099 non-null   int64
 6   Servicio telefónico         4099 non-null   object
 7   Líneas múltiples            4099 non-null   object
 8   Servicio de Internet        4099 non-null   object
 9   Protección contra Malware   4099 non-null   object
 10  Protección del dispositivo  4099 non-null   object
 11  Soporte técnico             4099 non-null   object
 12  Televisión en streaming     4099 non-null   object
 13  Películas en streaming      4099 non-null   object
 14  Contrato                    4099 non-null   object
 15  Facturación sin papel       4099 non-null   object
 16  Método de pago              4099 non-null   object
 17  Cargos mensuales (dólares)  4099 non-null   float64
 18  Cargos totales  (dólares)   4099 non-null   float64
 19  Deserción Cliente           4099 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 640.6+ KB

6. Cambia el tipo de dato de la columna "Antigüedad" a `float`. Para lograrlo, deberás reasignar esta columna con el nuevo tipo de dato. Luego, muestra las primeras 3 filas del DataFrame.

In [ ]:
df_1['Antigüedad'] = df_1['Antigüedad'].astype(float)
df_1['Antigüedad'].head(3)

0     1.0
1    34.0
2     2.0
Name: Antigüedad, dtype: float64

7. Verifica que la columna "Antigüedad" haya cambiado correctamente su tipo de dato a `float`.

In [ ]:
type(df_1['Antigüedad'])

pandas.core.series.Series

8. ¿Te parece correcto cambiar el tipo de dato de la columna "Cargos mensuales (dólares)" a tipo `int`? Justifica tu respuesta.

## Actividad 3

La empresa de telecomunicaciones te ha pedido que analices ciertas variables clave de sus clientes. Necesitas extraer columnas específicas, aplicar filtros básicos y comenzar a preparar los datos para futuros análisis más avanzados.

Puedes descargar la base de datos **<a href="https://docs.google.com/spreadsheets/d/1v6euDfqECe1HTJz0yFUrn7mmrt-rG9gG/export?format=xlsx
">aquí</a>** para responder las siguientes preguntas:

1. Muestra las cuatro primeras filas de las columnas "Género", "Antigüedad" y "Deserción Cliente" del DataFrame.

In [ ]:
Fila_1 = df_1['Género'].head(4)
Fila_2 = df_1['Antigüedad'].head(4)
Fila_3 = df_1['Deserción Cliente'].head(4)

print(Fila_1)
print(Fila_2)
print(Fila_3)

0     Femenino
1    Masculino
2    Masculino
3    Masculino
Name: Género, dtype: object
0     1.0
1    34.0
2     2.0
3    45.0
Name: Antigüedad, dtype: float64
0    No
1    No
2    Sí
3    No
Name: Deserción Cliente, dtype: object

2. ¿Cuántos clientes de la base de datos pertenecen al género masculino y cuántos al femenino?

In [ ]:
cantidad_genero = (df_1['Género'].value_counts())
print(cantidad_genero)

Género
Masculino    2083
Femenino     2016
Name: count, dtype: int64

3. Calcula el total que un cliente habría pagado si su cargo mensual se hubiera mantenido constante durante todo el tiempo en la empresa. Para esto, agrega una nueva columna al DataFrame llamada "Cargos acumulados (dólares)", que sea el resultado de multiplicar "Cargos mensuales" por "Antigüedad". Luego, muestra las primeras 5 filas del DataFrame para verificar que la nueva columna fue agregada correctamente.

In [ ]:
df_1['Cargos acumulados (dólares)'] = (df_1['Cargos mensuales (dólares)'] * df_1['Antigüedad'])
df_1['Cargos acumulados (dólares)'].head(5)

0      29.85
1    1936.30
2     107.70
3    1903.50
4     141.40
Name: Cargos acumulados (dólares), dtype: float64

4. Crea un nuevo DataFrame que contenga la información solo de los clientes cuyo "Servicio de Internet" es Fibra óptica. ¿Cuántas filas tiene este nuevo DataFrame? Muestra sus primeras 5 filas para comprobar que el filtro se aplicó correctamente.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

5. ¿Cuántos clientes con fibra óptica abandonaron la empresa? Muestra las primeras 5 filas del nuevo DataFrame para comprobar que el filtro se aplicó correctamente.

6. 🤖 Utiliza la IA de Google Colab para realizar el código que permita responder esta pregunta:

Calcula el promedio de "Cargos mensuales" de los clientes que cumplen estas tres condiciones al mismo tiempo:

* Tienen servicio de internet por Fibra óptica.
* Usan protección contra Malware.
* Continúan en la empresa.

Luego, realiza el mismo cálculo para los clientes que cumplen estas otras tres condiciones:
* Tienen servicio de internet por DSL.
* No usan protección contra Malware.
* Han abandonado la empresa.

Finalmente, compara ambos promedios y responde: ¿Cuál grupo paga más en promedio por los cargos mensuales? ¿ A qué crees que se podría deber esa diferencia?